---
useTabs: false
tabWidth: 2
singleQuote: false
trailingComma: "es5"
semi: true
bracketSpacing: true
arrowParens: "always"
parser: "typescript"
overrides:
  - files: "src/locales/translates/*.ts"
    options:
      printWidth: 120
  - files: "src/lib/zod/i18n.ts"
    options:
      printWidth: 100
